apiVersion: v1
kind: PersistentVolume
metadata:
   name: {{ template "mysql.fullname" . }}
   labels:
     type: local
spec:
   capacity:
     storage: {{ .Values.persistence.size }}
   accessModes:
    - {{ .Values.persistence.accessMode }}
   hostPath:
     path: {{ .Values.persistence.storagePath }}
